import { useMemo, useState } from 'react'
import { ArrowDownUp, CalendarClock, ChevronRight, CircleCheck, RefreshCw, ShieldCheck } from 'lucide-react'
import { pantryApi } from '../services/pantryApi'
import { useAsyncData } from '../hooks/useAsyncData'
import { Badge, EmptyState, ErrorState, LoadingCards, Modal } from '../components/common'
import { confidenceLabel, getPantryStatus } from '../utils/status'
import { daysLabel, fullDate, quantity } from '../utils/formatters'
import { useNavigate } from 'react-router-dom'
import pantryGroceries from '../assets/pantry-groceries.png'
import { GroceryImage } from '../utils/groceryImages'

const filters = ['All', 'Low Stock', 'Restock Soon', 'Expiring Soon', 'Healthy']
export default function PantryPage() {
 const { data: items, loading, error, refresh } = useAsyncData(pantryApi.getAll); const [filter, setFilter] = useState('All'); const [sort, setSort] = useState('Soonest to run out'); const [selected, setSelected] = useState(null); const navigate = useNavigate()
 const filtered = useMemo(() => (items || []).filter(item => filter === 'All' || getPantryStatus(item).label === filter).sort((a, b) => sort === 'Item name' ? a.name.localeCompare(b.name) : sort === 'Quantity' ? a.quantityRemaining - b.quantityRemaining : sort === 'Recently updated' ? new Date(b.lastPurchaseDate) - new Date(a.lastPurchaseDate) : a.daysRemaining - b.daysRemaining), [items, filter, sort])
 const attention = filtered.filter(item => getPantryStatus(item).key !== 'healthy'); const covered = filtered.filter(item => getPantryStatus(item).key === 'healthy'); const allAttention = (items || []).filter(item => getPantryStatus(item).key !== 'healthy'); const expiring = (items || []).filter(item => getPantryStatus(item).key === 'expiring').length
 return <><PageTitle title="Good afternoon, Kashish." subtitle="Here’s what’s happening in your pantry." action={<button className="btn-secondary" onClick={refresh} aria-label="Refresh pantry"><RefreshCw size={17} /> Refresh</button>} />
  {loading ? <LoadingCards count={3} /> : error ? <ErrorState title="Couldn't load your pantry." retry={refresh} /> : !items?.length ? <EmptyState icon="🧺" title="Your pantry is empty" action={<button className="btn-primary" onClick={() => navigate('/purchases')}>Log a Purchase</button>}>Start by logging your recent purchases. The agent will learn your consumption patterns and predict when you'll need to restock.</EmptyState> : <>
   <NextOrderPanel items={allAttention} onReview={() => navigate('/shopping-list')} />
   <PantryOutlook itemCount={items.length} attention={allAttention.length} healthy={items.length - allAttention.length} expiring={expiring} onAction={() => setFilter('Low Stock')} />
   <div className="mt-9 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-lg font-semibold tracking-tight text-slate-900">Your pantry</h2><p className="mt-1 text-sm text-slate-500">Keep the view focused on what matters right now.</p></div><label className="flex items-center gap-2 text-sm text-slate-500"><ArrowDownUp size={15}/><span className="sr-only">Sort pantry</span><select value={sort} onChange={e => setSort(e.target.value)} className="rounded-lg border-0 bg-transparent py-2 text-sm font-medium text-slate-700 focus:ring-2 focus:ring-emerald-500"><option>Soonest to run out</option><option>Item name</option><option>Quantity</option><option>Recently updated</option></select></label></div>
   <div className="mt-4 flex gap-4 overflow-x-auto border-b pb-2">{filters.map(name => <button key={name} onClick={() => setFilter(name)} className={`whitespace-nowrap border-b-2 px-1 py-2 text-sm font-medium transition ${filter === name ? 'border-emerald-700 text-emerald-800' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{name}</button>)}</div>
   {attention.length > 0 && <PantrySection title="Needs attention" description="A few things may need a place on your next order." items={attention} onSelect={setSelected} />}
   {covered.length > 0 && <PantrySection title={attention.length ? 'Looking good' : 'Your pantry looks good'} description={attention.length ? 'You have enough of these for now.' : 'Nothing needs your attention right now.'} items={covered} onSelect={setSelected} calm />}
   {!filtered.length && <EmptyState title="No items match this view">Try a different pantry status to see your items.</EmptyState>}
  </>}
  <PantryDetails item={selected} onClose={() => setSelected(null)} />
 </>
}
export function PageTitle({ title, subtitle, action }) { return <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-[28px] font-semibold tracking-[-.04em] text-slate-900 sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-500 sm:text-[15px]">{subtitle}</p></div>{action}</div> }
function NextOrderPanel({ items, onReview }) { if (!items.length) return null; return <section className="relative overflow-hidden rounded-[28px] bg-[#e5efd7] px-5 py-6 sm:px-8 sm:py-8"><div className="relative z-10 max-w-xl"><p className="text-sm font-medium text-[#517038]">Your next useful order</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.035em] text-[#171f11] sm:text-3xl">A little planning goes a long way.</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#55644a]">These essentials are likely to need attention soon. Ordering them together keeps your next shop simple.</p><div className="mt-6 grid max-w-lg grid-cols-3 divide-x divide-[#bed1a8] border-y border-[#bed1a8]">{items.map(item => <div key={item.id} className="px-3 py-3 first:pl-0"><GroceryImage name={item.name} decorative className="h-10 w-10 rounded-lg"/><p className="mt-2 text-sm font-medium text-[#171f11]">{item.name}</p><p className="mt-0.5 text-xs text-[#55644a]">{daysLabel(item.daysRemaining)}</p></div>)}</div><div className="mt-6 flex flex-wrap items-center gap-4"><button className="btn-primary bg-[#1b2514] hover:bg-[#10170c]" onClick={onReview}>Review shopping list <ChevronRight size={16}/></button><span className="text-sm text-[#55644a]">Estimated <strong className="font-semibold text-[#171f11]">₹155</strong></span></div></div><img src={pantryGroceries} alt="Fresh pantry groceries" className="pointer-events-none absolute -bottom-8 right-[-3rem] hidden h-[290px] w-[470px] object-contain object-bottom opacity-95 lg:block" /></section> }
function PantryOutlook({ itemCount, attention, healthy, expiring, onAction }) { return <section className="border-b border-slate-200 py-6 sm:py-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e9f1df] text-[#517038]"><CircleCheck size={18}/></div><div><p className="text-sm font-medium text-[#304422]">Pantry outlook</p><p className="mt-1 text-sm text-slate-500">{attention ? `${attention} item${attention > 1 ? 's' : ''} deserve a look this week.` : `All ${itemCount} items are in a healthy range.`}</p></div></div><div className="flex flex-wrap items-center gap-x-7 gap-y-3"><Metric value={itemCount} label="items tracked" /><Metric value={healthy} label="well stocked" /><Metric value={expiring} label="expiring soon" />{attention > 0 && <button onClick={onAction} className="text-sm font-medium text-[#3e6426] hover:text-[#1b2514]">View attention items</button>}</div></div></section> }
function Metric({ value, label }) { return <div><p className="text-xl font-semibold tracking-tight text-slate-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div> }
function PantrySection({ title, description, items, onSelect, calm = false }) { return <section className="mt-8"><div className="flex items-baseline justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-tight text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><span className="text-xs font-medium text-slate-400">{items.length} item{items.length !== 1 ? 's' : ''}</span></div>{calm ? <div className="mt-4 divide-y border-y border-slate-200">{items.map(item => <PantryRow item={item} key={item.id} onClick={() => onSelect(item)} />)}</div> : <div className="mt-4 grid gap-3 sm:grid-cols-3">{items.map(item => <PantryTile item={item} key={item.id} onClick={() => onSelect(item)} />)}</div>}</section> }
function PantryTile({ item, onClick }) { const status = getPantryStatus(item); return <button onClick={onClick} className="group rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-[#b9d89d] hover:shadow-sm"><div className="relative"><GroceryImage name={item.name} className="mx-auto aspect-square h-32 rounded-xl transition duration-200 group-hover:scale-[1.03]"/><ChevronRight className="absolute right-0 top-1 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-[#3e6426]" size={18}/></div><p className="mt-5 font-semibold text-[#171f11]">{item.name}</p><p className="mt-1 text-xl font-semibold tracking-tight text-slate-800">{quantity(item.quantityRemaining, item.unit)}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs text-slate-500">Runs out {daysLabel(item.daysRemaining)}</span><Badge className={status.className}>{status.label}</Badge></div></button> }
function PantryRow({ item, onClick }) { const status = getPantryStatus(item); return <button onClick={onClick} className="group flex w-full items-center gap-3 py-4 text-left transition hover:bg-slate-50 sm:gap-4 sm:px-2"><GroceryImage name={item.name} className="h-12 w-12 rounded-xl"/><div className="min-w-0 flex-1"><p className="font-medium text-slate-900">{item.name}</p><p className="mt-0.5 text-sm text-slate-500">~{quantity(item.quantityRemaining, item.unit)} remaining</p></div><div className="hidden text-right sm:block"><p className="text-sm font-medium text-slate-800">{daysLabel(item.daysRemaining)}</p><p className="mt-0.5 text-xs text-slate-400">expected run-out</p></div><Badge className={`${status.className} hidden sm:inline-flex`}>{status.label}</Badge><ChevronRight className="shrink-0 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-slate-700" size={18}/></button> }
function PantryDetails({ item, onClose }) { if (!item) return null; const status = getPantryStatus(item); return <Modal open={!!item} title={item.name} onClose={onClose}><div className="flex items-center gap-4 border-b pb-5"><GroceryImage name={item.name} className="h-20 w-20 rounded-2xl"/><div><Badge className={status.className}>{status.label}</Badge><p className="mt-2 text-sm text-slate-500">Last purchased {fullDate(item.lastPurchaseDate)}</p></div></div><dl className="mt-5 grid grid-cols-2 gap-x-5 gap-y-5"><Detail label="Current estimate" value={quantity(item.quantityRemaining, item.unit)} /><Detail label="Consumption pattern" value={`~${quantity(item.consumptionRate, item.consumptionUnit)}`} /><Detail label="Predicted run-out" value={fullDate(item.predictedRunoutDate)} /><Detail label="Model confidence" value={`${Math.round(item.confidence * 100)}% · ${confidenceLabel(item.confidence)}`} /><Detail label="Expiry" value={item.expiryDate ? fullDate(item.expiryDate) : 'Not tracked'} /><Detail label="Days remaining" value={`Likely ${daysLabel(item.daysRemaining)}`} /></dl><div className="mt-7"><h3 className="flex items-center gap-2 font-semibold text-slate-900"><CalendarClock size={17} className="text-emerald-700" /> Recent purchases</h3>{item.history?.length ? <ul className="mt-3 divide-y border-y">{item.history.map((entry, i) => <li className="flex justify-between py-2.5 text-sm" key={i}><span className="text-slate-500">{entry.date}</span><span className="font-medium">{entry.quantity}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No detailed purchase history is available yet.</p>}</div><div className="mt-6 flex items-start gap-2 border-l-2 border-blue-300 bg-blue-50/60 p-3 text-sm text-blue-900"><ShieldCheck size={17} className="mt-0.5 shrink-0" /> This is an estimate based on your purchase pattern, not a certainty.</div></Modal> }
function Detail({ label, value }) { return <div><dt className="text-xs font-medium text-slate-400">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-800">{value}</dd></div> }
