import { useMemo, useState } from 'react'
import { Download, FileUp, Pencil, Plus, Search, Trash2, Upload } from 'lucide-react'
import { purchasesApi } from '../services/purchasesApi'
import { useAsyncData } from '../hooks/useAsyncData'
import { Card, EmptyState, ErrorState, Modal, Skeleton, Spinner } from '../components/common'
import { money, shortDate } from '../utils/formatters'
import { PageTitle } from './PantryPage'
import { GroceryImage } from '../utils/groceryImages'
const units = ['piece', 'loaf', 'packet', 'kg', 'g', 'litre', 'ml', 'dozen', 'bottle', 'box', 'other']; const categories = ['Dairy', 'Bakery', 'Eggs', 'Beverages', 'Grains', 'Snacks', 'Fruits', 'Vegetables', 'Household', 'Other']
const blank = () => ({ itemName: '', quantity: '', unit: 'piece', purchaseDate: new Date().toISOString().slice(0, 10), price: '', category: '', expiryDate: '', notes: '' })
export default function PurchasesPage({ notify }) {
 const { data, loading, error, refresh } = useAsyncData(purchasesApi.getAll); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [form, setForm] = useState(null); const [deleting, setDeleting] = useState(null); const [importOpen, setImportOpen] = useState(false)
 const rows = useMemo(() => (data || []).filter(p => p.itemName.toLowerCase().includes(query.toLowerCase()) && (category === 'All' || p.category === category)), [data, query, category])
 const save = async values => { if (values.id) await purchasesApi.update(values.id, values); else await purchasesApi.create(values); setForm(null); await refresh(); notify(values.id ? 'Purchase updated. Pantry estimates are being recalculated.' : 'Purchase logged successfully. Your pantry prediction has been updated.') }
 const remove = async () => { await purchasesApi.remove(deleting.id); setDeleting(null); await refresh(); notify('Purchase deleted. Pantry estimates are being recalculated.') }
 return <><PageTitle title="Purchase History" subtitle="Teach your pantry agent what you buy." action={<div className="flex gap-2"><button className="btn-secondary" onClick={() => setImportOpen(true)}><FileUp size={17} /> <span className="hidden sm:inline">Import History</span></button><button className="btn-primary" onClick={() => setForm(blank())}><Plus size={17} /> Log Purchase</button></div>} />
 {loading ? <HistorySkeleton /> : error ? <ErrorState title="Couldn't load your purchases." retry={refresh} /> : !data?.length ? <EmptyState title="No purchases yet" action={<button className="btn-primary" onClick={() => setForm(blank())}>Log a Purchase</button>}>Log a recent purchase to start teaching your pantry agent.</EmptyState> : <><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><label className="relative block sm:w-80"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><span className="sr-only">Search purchases</span><input value={query} onChange={e => setQuery(e.target.value)} className="field mt-0 pl-9" placeholder="Search purchases" /></label><select className="field mt-0 sm:w-44" value={category} onChange={e => setCategory(e.target.value)}><option>All</option>{categories.map(x => <option key={x}>{x}</option>)}</select></div><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-semibold">Item</th><th className="px-5 py-3 font-semibold">Quantity</th><th className="px-5 py-3 font-semibold">Date</th><th className="px-5 py-3 font-semibold">Price</th><th className="px-5 py-3 font-semibold">Category</th><th className="px-5 py-3 font-semibold"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(p => <PurchaseRow key={p.id} purchase={p} onEdit={() => setForm(p)} onDelete={() => setDeleting(p)} />)}</tbody></table></div><div className="divide-y md:hidden">{rows.map(p => <PurchaseMobile key={p.id} purchase={p} onEdit={() => setForm(p)} onDelete={() => setDeleting(p)} />)}</div></Card>{!rows.length && <p className="py-8 text-center text-sm text-slate-500">No purchases match your filters.</p>}</>}
 <PurchaseForm initial={form} onClose={() => setForm(null)} onSave={save} /><DeleteDialog purchase={deleting} onClose={() => setDeleting(null)} onDelete={remove} /><ImportHistory open={importOpen} onClose={() => setImportOpen(false)} notify={notify} />
 </>
}
function PurchaseRow({ purchase: p, onEdit, onDelete }) { return <tr className="border-t transition hover:bg-slate-50"><td className="px-5 py-3"><div className="flex items-center gap-3"><GroceryImage name={p.itemName} className="h-11 w-11 rounded-xl"/><span className="font-semibold text-slate-800">{p.itemName}</span></div></td><td className="px-5 py-4 text-slate-600">{p.quantity} {p.unit}</td><td className="px-5 py-4 text-slate-600">{shortDate(p.purchaseDate)}</td><td className="px-5 py-4 text-slate-600">{p.price ? money(p.price) : '—'}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{p.category || 'Other'}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><IconButton title="Edit purchase" onClick={onEdit}><Pencil size={16}/></IconButton><IconButton title="Delete purchase" onClick={onDelete} danger><Trash2 size={16}/></IconButton></div></td></tr> }
function PurchaseMobile({ purchase: p, onEdit, onDelete }) { return <div className="p-4"><div className="flex justify-between gap-3"><div className="flex gap-3"><GroceryImage name={p.itemName} className="h-14 w-14 rounded-xl"/><div><p className="font-semibold">{p.itemName}</p><p className="mt-1 text-sm text-slate-500">{p.quantity} {p.unit} · {shortDate(p.purchaseDate)}</p><p className="mt-2 text-sm font-semibold text-slate-700">{p.price ? money(p.price) : 'Price not added'}</p></div></div><div className="flex gap-1"><IconButton title="Edit purchase" onClick={onEdit}><Pencil size={16}/></IconButton><IconButton title="Delete purchase" onClick={onDelete} danger><Trash2 size={16}/></IconButton></div></div></div> }
function IconButton({ children, title, onClick, danger }) { return <button title={title} aria-label={title} onClick={onClick} className={`rounded-lg p-2 transition ${danger ? 'text-rose-600 hover:bg-rose-50' : 'text-slate-500 hover:bg-slate-100'}`}>{children}</button> }
function PurchaseForm({ initial, onClose, onSave }) { const [values, setValues] = useState(blank()); const [key, setKey] = useState(''); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false); const active = initial ? { ...blank(), ...initial } : null; if (active && key !== active.id + active.itemName) { setKey(active.id + active.itemName); setValues(active); setErrors({}) }
 const change = e => setValues(v => ({ ...v, [e.target.name]: e.target.value })); const submit = async e => { e.preventDefault(); const found = {}; if (!values.itemName.trim()) found.itemName = 'Item name is required.'; if (!values.quantity || Number(values.quantity) <= 0) found.quantity = 'Enter a quantity greater than zero.'; if (!values.purchaseDate) found.purchaseDate = 'Purchase date is required.'; setErrors(found); if (Object.keys(found).length) return; setSaving(true); try { await onSave({ ...values, quantity: Number(values.quantity), price: values.price === '' ? null : Number(values.price) }) } finally { setSaving(false) } }
 return <Modal open={!!initial} title={initial?.id ? 'Edit purchase' : 'Log a purchase'} onClose={onClose} wide><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Input label="Item name" name="itemName" value={values.itemName} onChange={change} error={errors.itemName} required /><Input label="Quantity" name="quantity" type="number" min="0.01" step="any" value={values.quantity} onChange={change} error={errors.quantity} required /><Select label="Unit" name="unit" value={values.unit} onChange={change} options={units} /><Input label="Purchase date" name="purchaseDate" type="date" value={values.purchaseDate} onChange={change} error={errors.purchaseDate} required /><Input label="Price (optional)" name="price" type="number" min="0" step="any" value={values.price} onChange={change} prefix="₹" /><Select label="Category (optional)" name="category" value={values.category} onChange={change} options={categories} empty="Select category" /><Input label="Expiry date (optional)" name="expiryDate" type="date" value={values.expiryDate} onChange={change} /><label className="sm:col-span-2"><span className="label">Notes (optional)</span><textarea name="notes" value={values.notes} onChange={change} rows="3" className="field resize-none" placeholder="Bought during weekend grocery order" /></label></div><div className="mt-7 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? <Spinner label="Saving" /> : 'Save purchase'}</button></div></form></Modal> }
function Input({ label, name, prefix, error, ...props }) { return <label><span className="label">{label}{props.required && <span className="text-rose-500"> *</span>}</span><div className="relative">{prefix && <span className="absolute left-3 top-2.5 text-sm text-slate-500">{prefix}</span>}<input name={name} {...props} className={`field ${prefix ? 'pl-7' : ''} ${error ? 'border-rose-400 focus:border-rose-500 focus:ring-rose-100' : ''}`} /></div>{error && <p className="mt-1 text-xs font-medium text-rose-600">{error}</p>}</label> }
function Select({ label, name, options, empty, ...props }) { return <label><span className="label">{label}</span><select name={name} {...props} className="field">{empty && <option value="">{empty}</option>}{options.map(x => <option key={x}>{x}</option>)}</select></label> }
function DeleteDialog({ purchase, onClose, onDelete }) { const [busy, setBusy] = useState(false); return <Modal open={!!purchase} title="Delete purchase?" onClose={onClose}><p className="text-sm leading-6 text-slate-600">This may change your pantry predictions. This action cannot be undone.</p><div className="mt-7 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn bg-rose-600 text-white hover:bg-rose-700" disabled={busy} onClick={async () => { setBusy(true); await onDelete(); setBusy(false) }}>{busy ? <Spinner label="Deleting" /> : 'Delete'}</button></div></Modal> }
function ImportHistory({ open, onClose, notify }) { const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); setResult(await purchasesApi.importHistory()); setBusy(false) }; return <Modal open={open} title="Import Purchase History" onClose={onClose}><p className="text-sm text-slate-600">Upload or import your previous order history. You can still log purchases manually.</p>{!result ? <><label className="mt-5 flex cursor-pointer flex-col items-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center hover:border-emerald-500"><Upload className="mb-2 text-emerald-700" /><span className="font-semibold text-slate-800">Select File</span><span className="mt-1 text-xs text-slate-500">Supported: CSV, JSON</span><input type="file" className="sr-only" accept=".csv,.json" onChange={run}/></label><div className="my-5 flex items-center gap-3 text-xs font-semibold text-slate-400 before:h-px before:flex-1 before:bg-slate-200 after:h-px after:flex-1 after:bg-slate-200">OR</div><button className="btn-secondary w-full" onClick={run} disabled={busy}>{busy ? <Spinner label="Checking source" /> : <><Download size={17}/> Import from connected source</>}</button><p className="mt-4 text-center text-xs text-slate-500">History import is not connected to a live source yet.</p></> : <div className="mt-5 rounded-2xl bg-emerald-50 p-5"><p className="text-2xl font-bold text-emerald-900">{result.found} purchases found</p><p className="mt-3 text-sm text-emerald-800">✓ {result.ready} ready to import<br/>⚠ {result.review} need review</p><div className="mt-5 flex gap-2"><button className="btn-secondary flex-1">Review</button><button className="btn-primary flex-1" onClick={() => { notify('Purchase history import is ready for review.'); onClose() }}>Import All</button></div></div>}</Modal> }
function HistorySkeleton() { return <Card className="p-5">{[1,2,3,4,5].map(x => <div className="flex gap-5 border-b py-4" key={x}><Skeleton className="h-5 w-1/4"/><Skeleton className="h-5 w-1/6"/><Skeleton className="h-5 w-1/6"/></div>)}</Card> }
