import { useState } from 'react'
import { CheckCircle2, ChevronRight, Moon, ShoppingBasket, XCircle } from 'lucide-react'
import { remindersApi } from '../services/remindersApi'
import { useAsyncData } from '../hooks/useAsyncData'
import { Badge, EmptyState, ErrorState, LoadingCards, Modal } from '../components/common'
import { money, shortDate } from '../utils/formatters'
import { PageTitle } from './PantryPage'
import { useNavigate } from 'react-router-dom'
import { GroceryImage } from '../utils/groceryImages'
export default function RemindersPage({ notify }) {
 const { data, loading, error, refresh } = useAsyncData(remindersApi.getAll); const [snooze, setSnooze] = useState(null); const [dismiss, setDismiss] = useState(null); const navigate = useNavigate(); const recommended = data?.find(x => x.status === 'pending' && x.type === 'restock'); const later = data?.filter(x => x.id !== recommended?.id) || []
 const handleSnooze = async days => { await remindersApi.snooze(snooze.id, days); setSnooze(null); await refresh(); notify(`Reminder snoozed for ${days === 1 ? 'tomorrow' : `${days} days`}.`) }; const handleDismiss = async () => { await remindersApi.dismiss(dismiss.id); setDismiss(null); await refresh(); notify('Reminder dismissed. Your plan has been updated.') }
 return <><PageTitle title="Your next order" subtitle="We’ve grouped a few things that will need attention soon." />{loading ? <LoadingCards count={2} /> : error ? <ErrorState title="Couldn't load your reminders." retry={refresh} /> : !data?.length ? <EmptyState icon="✓" title="You're all set.">Nothing needs restocking right now.</EmptyState> : <>{recommended && <RecommendedOrder reminder={recommended} onReview={() => navigate('/shopping-list')} onSnooze={() => setSnooze(recommended)} onDismiss={() => setDismiss(recommended)} />}{later.length > 0 && <section className="mt-10"><h2 className="text-lg font-semibold tracking-tight text-slate-900">Later on</h2><p className="mt-1 text-sm text-slate-500">We’ll wait until these are more useful to order together.</p><div className="mt-4 divide-y border-y">{later.map(reminder => <LaterRow key={reminder.id} reminder={reminder} onReview={() => navigate('/shopping-list')} onSnooze={() => setSnooze(reminder)} onDismiss={() => setDismiss(reminder)} />)}</div></section>}</>}<SnoozeDialog reminder={snooze} onClose={() => setSnooze(null)} onChoose={handleSnooze}/><DismissDialog reminder={dismiss} onClose={() => setDismiss(null)} onConfirm={handleDismiss}/></>
}
function RecommendedOrder({ reminder, onReview, onSnooze, onDismiss }) { return <section className="rounded-[28px] bg-[#e5efd7] px-5 py-7 sm:px-8 sm:py-9"><div className="grid gap-8 xl:grid-cols-[1fr_285px]"><div><p className="text-sm font-medium text-[#517038]">Your next useful order</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.035em] text-[#171f11]">A small restock, timed well</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#55644a]">Ordering these together means you can cover {reminder.items.length} essentials in one trip—without a separate low-value order.</p><div className="mt-7 grid gap-x-5 divide-y border-y border-[#bed1a8] sm:grid-cols-3 sm:divide-x sm:divide-y-0">{reminder.items.map(item => <div key={item.itemName} className="flex items-center gap-3 py-3 sm:block sm:px-4 sm:py-1 first:pl-0"><GroceryImage name={item.itemName} decorative className="h-14 w-14 rounded-xl"/><div className="sm:mt-3"><p className="text-sm font-medium text-[#171f11]">{item.itemName}</p><p className="mt-0.5 text-xs text-[#55644a]">{item.reason}</p></div></div>)}</div><div className="mt-7 flex flex-wrap gap-2"><button className="btn-primary bg-[#1b2514] hover:bg-[#10170c]" onClick={onReview}><ShoppingBasket size={16}/> Review list</button><button className="btn-secondary bg-white/70" onClick={onSnooze}><Moon size={16}/> Snooze</button><button title="Dismiss reminder" aria-label="Dismiss reminder" className="rounded-lg px-3 text-[#55644a] hover:bg-white/60 hover:text-rose-600" onClick={onDismiss}><XCircle size={18}/></button></div></div><aside className="border-l-0 border-[#bed1a8] xl:border-l xl:pl-7"><p className="text-sm text-[#55644a]">Estimated total</p><p className="mt-1 text-3xl font-semibold tracking-tight text-[#171f11]">{money(reminder.estimatedTotal)}</p><p className="mt-5 text-sm text-[#55644a]">Free delivery <span className="font-medium text-[#171f11]">{money(reminder.freeDeliveryThreshold)}</span></p><p className="mt-3 flex items-start gap-2 text-sm font-medium text-[#3e6426]"><CheckCircle2 size={17} className="mt-0.5 shrink-0"/> Covers {reminder.items.length} upcoming restocks</p><p className="mt-5 border-t border-[#bed1a8] pt-4 text-xs leading-5 text-[#55644a]">Why these items? {reminder.reasons[0]}</p></aside></div></section> }
function LaterRow({ reminder, onReview, onSnooze, onDismiss }) { const isSnoozed = reminder.status === 'snoozed'; return <div className="flex flex-wrap items-center gap-3 py-4 sm:px-2"><div className="min-w-44 flex-1"><p className="font-medium text-slate-900">{isSnoozed ? `Snoozed for ${reminder.snoozedDays} day${reminder.snoozedDays > 1 ? 's' : ''}` : shortDate(reminder.scheduledDate)}</p><p className="mt-1 text-sm text-slate-500">{reminder.items.map(item => item.itemName).join(', ')}</p></div><p className="hidden max-w-sm text-sm text-slate-500 lg:block">{reminder.reasons[0]}</p>{isSnoozed ? <Badge className="bg-slate-100 text-slate-600 ring-slate-200">Snoozed</Badge> : <Badge className="bg-blue-50 text-blue-700 ring-blue-100">Plan ahead</Badge>}<button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Review shopping list" onClick={onReview}><ChevronRight size={18}/></button>{!isSnoozed && <button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Snooze reminder" onClick={onSnooze}><Moon size={16}/></button>}<button className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label="Dismiss reminder" onClick={onDismiss}><XCircle size={16}/></button></div> }
function SnoozeDialog({ reminder, onClose, onChoose }) { return <Modal open={!!reminder} title="Snooze reminder" onClose={onClose}><p className="text-sm text-slate-600">When would you like us to bring this plan back?</p><div className="mt-5 grid gap-2">{[[1, 'Tomorrow'], [3, '3 days'], [7, 'Next week']].map(([days, label]) => <button key={days} onClick={() => onChoose(days)} className="flex items-center justify-between rounded-lg border p-3 text-left text-sm font-medium hover:border-emerald-500 hover:bg-emerald-50">{label}<ChevronRight size={16} className="text-slate-400"/></button>)}</div></Modal> }
function DismissDialog({ reminder, onClose, onConfirm }) { return <Modal open={!!reminder} title="Dismiss reminder?" onClose={onClose}><p className="text-sm leading-6 text-slate-600">Dismissing this reminder may mean placing a separate low-value order later.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn bg-rose-600 text-white hover:bg-rose-700" onClick={onConfirm}>Dismiss</button></div></Modal> }
