import { useMemo, useState } from 'react'
import { Check, CheckCircle2, ChevronDown, Circle, Edit3, LoaderCircle, Plus, ShoppingBasket, Trash2, Undo2 } from 'lucide-react'
import { shoppingApi } from '../services/shoppingApi'
import { Card, Modal, Spinner } from '../components/common'
import { money, quantity } from '../utils/formatters'
import { PageTitle } from './PantryPage'
import { useNavigate } from 'react-router-dom'
import pantryGroceries from '../assets/pantry-groceries.png'
import { GroceryImage } from '../utils/groceryImages'
const prompts = ['Breakfast for 3 tomorrow', 'Dinner for 4, making pasta', 'Things I need for a weekend trip', 'Restock my usual groceries']
export default function ShoppingListPage({ notify }) {
 const [intent, setIntent] = useState('Dinner for 4, making pasta'); const [list, setList] = useState(null); const [loading, setLoading] = useState(false); const [addOpen, setAddOpen] = useState(false); const [confirmed, setConfirmed] = useState(false); const navigate = useNavigate()
 const generate = async () => { if (!intent.trim()) return; setLoading(true); try { setList(await shoppingApi.generate(intent)); setConfirmed(false); notify('Your shopping list is ready to review.') } finally { setLoading(false) } }
 const update = (id, patch) => setList(current => ({ ...current, items: current.items.map(item => item.id === id ? { ...item, ...patch } : item) })); const active = list?.items.filter(x => !x.removed) || []; const total = active.reduce((sum, x) => sum + (x.checked ? 0 : Number(x.estimatedPrice || 0)), 0)
 const confirm = async () => { setLoading(true); try { await shoppingApi.confirm(list.id, active); setConfirmed(true); notify('Shopping list confirmed and saved to your pantry agent.') } finally { setLoading(false) } }
 return <><PageTitle title="Shopping List" subtitle="Turn a plan into a thoughtful, pantry-aware list." />
 <section className="relative overflow-hidden rounded-[28px] bg-[#eef4e7] px-5 py-6 sm:px-8 sm:py-8"><div className="relative z-10 max-w-2xl"><div className="flex items-center gap-2 text-sm font-medium text-[#517038]"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#1b2514] text-[#c6e395]"><ShoppingBasket size={15}/></span> What are you planning?</div><div className="mt-4 rounded-xl border border-[#d9e5ca] bg-white p-2 shadow-sm sm:flex sm:items-center"><textarea value={intent} onChange={e => setIntent(e.target.value)} rows="2" className="block min-h-12 w-full resize-none border-0 bg-transparent px-2 py-2 text-base outline-none placeholder:text-slate-400 focus:ring-0" placeholder="Dinner for 4, making pasta" /><button className="btn-primary shrink-0 bg-[#1b2514] hover:bg-[#10170c] sm:ml-2" disabled={!intent.trim() || loading} onClick={generate}>{loading && !confirmed ? <Spinner label="Generating" /> : 'Generate'}</button></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{prompts.map(prompt => <button key={prompt} onClick={() => setIntent(prompt)} className="whitespace-nowrap rounded-full px-2 py-1 text-xs text-[#66735b] hover:bg-white/60 hover:text-[#171f11]">{prompt}</button>)}</div><img src={pantryGroceries} alt="Fresh groceries for your pantry" className="mx-auto -mb-7 mt-2 h-24 w-52 object-contain sm:hidden" /></div><img src={pantryGroceries} alt="" aria-hidden="true" className="pointer-events-none absolute -bottom-14 -right-14 hidden h-[280px] w-[430px] max-w-none object-contain xl:block" /></section>
 {list && !confirmed && <div className="mt-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><Card className="overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-bold text-slate-900">Your shopping list</h2><p className="mt-1 text-sm text-slate-500">{list.intent} · Make any changes before you save the plan.</p></div><div className="divide-y">{list.items.filter(item => !item.removed).map(item => <ListItem item={item} key={item.id} onUpdate={update} />)}</div>{list.items.some(item => item.removed) && <div className="border-t bg-slate-50 px-5 py-3">{list.items.filter(item => item.removed).map(item => <button key={item.id} className="mr-3 inline-flex items-center gap-1 text-xs font-semibold text-slate-600 hover:text-emerald-700" onClick={() => update(item.id, { removed: false })}><Undo2 size={13}/> Restore {item.name}</button>)}</div>}<div className="p-4"><button className="btn-secondary w-full" onClick={() => setAddOpen(true)}><Plus size={17}/> Add item</button></div></Card><OrderSummary items={active} total={total} threshold={list.freeDeliveryThreshold} onConfirm={confirm} loading={loading} /></div>}
 {confirmed && <Confirmation onPantry={() => navigate('/pantry')} onReminders={() => navigate('/reminders')} />}
 <AddItem open={addOpen} onClose={() => setAddOpen(false)} onAdd={item => { setList(current => ({ ...current, items: [...current.items, { ...item, id: crypto.randomUUID(), estimatedPrice: Number(item.estimatedPrice || 0), checked: false } ] })); setAddOpen(false); notify(`${item.name} added to your list.`) }} />
 </>
}
function ListItem({ item, onUpdate }) { const [editing, setEditing] = useState(false); const [amount, setAmount] = useState(item.quantity); const [unit, setUnit] = useState(item.unit); return <div className="p-4 sm:p-5"><div className="flex gap-3"><button className={`mt-0.5 shrink-0 rounded-full ${item.checked ? 'text-emerald-600' : 'text-slate-300 hover:text-emerald-600'}`} onClick={() => onUpdate(item.id, { checked: !item.checked })} aria-label={`Mark ${item.name} ${item.checked ? 'not done' : 'done'}`}>{item.checked ? <CheckCircle2 size={22}/> : <Circle size={22}/>}</button><GroceryImage name={item.name} className="h-14 w-14 rounded-xl sm:h-16 sm:w-16"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className={`font-bold ${item.checked ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{item.name}</p><p className="mt-0.5 text-xs text-slate-500">{item.category || 'Other'} · {item.estimatedPrice ? money(item.estimatedPrice) : 'Price pending'}</p></div><div className="flex items-center gap-1"><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label={`Edit ${item.name}`} onClick={() => setEditing(x => !x)}><Edit3 size={16}/></button><button className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label={`Remove ${item.name}`} onClick={() => onUpdate(item.id, { removed: true })}><Trash2 size={16}/></button></div></div>{editing ? <div className="mt-3 flex gap-2"><input type="number" min="0" className="field mt-0 w-24" value={amount} onChange={e => setAmount(e.target.value)}/><input className="field mt-0 w-24" value={unit} onChange={e => setUnit(e.target.value)}/><button className="btn-primary px-3" onClick={() => { onUpdate(item.id, { quantity: Number(amount), unit }); setEditing(false) }}><Check size={16}/></button></div> : <p className="mt-2 text-sm font-semibold text-slate-600">{quantity(item.quantity, item.unit)}</p>}{item.duplicateWarning && <div className="mt-3 rounded-xl border border-amber-100 bg-amber-50 p-3"><p className="text-sm font-bold text-amber-900">You already have ~{item.pantryQuantity} remaining.</p><p className="mt-1 text-xs text-amber-800">Do you still need another bottle?</p><div className="mt-2 flex gap-2"><button className="rounded-lg bg-white px-2.5 py-1.5 text-xs font-semibold text-amber-800 ring-1 ring-amber-200" onClick={() => onUpdate(item.id, { duplicateWarning: false })}>Keep</button><button className="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-amber-800 hover:bg-amber-100" onClick={() => onUpdate(item.id, { removed: true })}>Remove</button></div></div>}</div></div></div> }
function OrderSummary({ items, total, threshold, onConfirm, loading }) { const difference = total - threshold; return <Card className="sticky top-5 p-5"><h2 className="text-lg font-bold">Order summary</h2><p className="mt-1 text-sm text-slate-500">{items.filter(x => !x.checked).length} items to pick up</p><div className="mt-5 space-y-3 border-y py-4 text-sm"><div className="flex justify-between"><span className="text-slate-500">Estimated total</span><span className="font-bold text-slate-900">{money(total)}</span></div><div className="flex justify-between"><span className="text-slate-500">Free-delivery threshold</span><span className="font-semibold">{money(threshold)}</span></div></div><p className={`mt-4 rounded-xl p-3 text-sm font-medium ${difference >= 0 ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{difference >= 0 ? `✓ ${money(difference)} above threshold` : `${money(-difference)} away from threshold`}</p><button className="btn-primary mt-5 w-full" onClick={onConfirm} disabled={!items.length || loading}>{loading ? <Spinner label="Confirming" /> : 'Confirm shopping list'}</button><p className="mt-3 text-center text-xs leading-5 text-slate-500">This saves your shopping plan. It does not place an order.</p></Card> }
function AddItem({ open, onClose, onAdd }) { const [values, setValues] = useState({ name: '', quantity: 1, unit: 'piece', estimatedPrice: '' }); return <Modal open={open} title="Add item" onClose={onClose}><div className="space-y-4"><label><span className="label">Item name</span><input autoFocus className="field" value={values.name} onChange={e => setValues(v => ({ ...v, name: e.target.value }))}/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Quantity</span><input type="number" min="0.1" className="field" value={values.quantity} onChange={e => setValues(v => ({ ...v, quantity: e.target.value }))}/></label><label><span className="label">Unit</span><input className="field" value={values.unit} onChange={e => setValues(v => ({ ...v, unit: e.target.value }))}/></label></div><label><span className="label">Estimated price (optional)</span><input type="number" min="0" className="field" value={values.estimatedPrice} onChange={e => setValues(v => ({ ...v, estimatedPrice: e.target.value }))}/></label></div><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={!values.name.trim() || Number(values.quantity) <= 0} onClick={() => onAdd({ ...values, quantity: Number(values.quantity) })}>Add item</button></div></Modal> }
function Confirmation({ onPantry, onReminders }) { return <Card className="mt-6 p-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-emerald-700"><CheckCircle2 size={30}/></div><h2 className="mt-5 text-2xl font-bold text-slate-900">Shopping list confirmed</h2><p className="mt-2 text-sm text-slate-500">Your items are ready to order. The list has been saved to your pantry agent.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="btn-primary" onClick={onPantry}>Back to pantry</button><button className="btn-secondary" onClick={onReminders}>View reminders</button></div></Card> }
